package com.example.exploregang.util

enum class UserResults {
    EMAILANDPASSEMPTY,
    CORRECTCREDENTIALS,
    EMAILEMPTY,
    EMAILFORMAT,
    PASSEMPTY,
    PASSWORDFORMAT,
    WRONGPASSWORD,
    SUCCESS,
    FAILURE,
    NAMEMPTY,
    DNIINVALID,
    FUTUREBIRTH,
    NODATEBRITH,
    INVALIDPHONE,
    EMAILSHORT,
    PASSWORDSHORT,
    TUTOREMAILSHORT,
    TUTOREMAILFORMAT,
    TUTORNAMESHORT,
    TUTORPHONEINVALID,
    SURNAMEEMPTY,
    NICKEMPTY,
    PASSWORDSDONTMATCH,
    ERRORREAUTENTICATION,
    ERRORCHANGEPASSWORD
}